### ISSUE TITLE
Unable to clone & run locally

### ISSUE THREAD

**Issue by alechp** [bbodi/notecalc3#1]
## Summary

1. Need wasm-pack and serve binaries
2. `#![feature]` may not be used on the stable release channel
3. When running, it seems to launch the notecalc home page instead of the calculator itself

--- 
### Screenshots
 
<details><summary>Without wasm-pack</summary>
<img src="https://user-images.githubusercontent.com/3058939/99687980-1e509780-2a3a-11eb-8cf6-3a690aed6057.png" />
</details>

<details><summary>With wasm-pack, without serve</summary>
<img src="https://user-images.githubusercontent.com/3058939/99687964-185ab680-2a3a-11eb-9531-5d3cbef81c29.png" />
</details>

### Update README

```sh
# 1. clone repo
git clone https://github.com/bbodi/notecalc3.git

# 2. install global binaries required for compile_and_run
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

# 3. compile and run
cd ../
./compile_and_run.bat
```

### Update compile_and_run.bat

Use npx for serve to avoid global install

<details><summary>From...</summary>
<pre><code>
cd frontend-web
wasm-pack build --debug --target no-modules
cd ..
serve .
</code></pre></summary>
</details>

<details><summary>To...</summary>
<pre><code>
cd frontend-web
wasm-pack build --debug --target no-modules
cd ..
npx serve .
```
</code></pre>
</details>

--- 

## 2. Stable release channel

#### Screenshots 

<details><summary>Stable release channel error</summary>
<img src="https://user-images.githubusercontent.com/3058939/99688364-8b642d00-2a3a-11eb-8ecf-83cebadc1259.png" />
</details>

<details><summary>Re-running rustup</summary>
<img src="https://user-images.githubusercontent.com/3058939/99688146-4fc96300-2a3a-11eb-9f3c-f2d8ae2f8aa6.png" />
</details>

#### Questions
This is obviously not a new issue https://github.com/rust-lang/rust/issues/37877

Despite re-running rustup, there's still an issue. I'm a rust novice and I'm confident this is an issue with my system, not notecalc. 

Is there a rust RC (eg. like a nightly release) that I need to be using?

---

## 3. Showing website instead of calculator

#### Screenshots
<details><summary>Serve working (expected)</summary>
<img src="https://user-images.githubusercontent.com/3058939/99688611-dc742100-2a3a-11eb-94ae-0f59faf01bcf.png" />
</details>

<details><summary>Notecalc home page showing (unexpected)</summary>
<img src="https://user-images.githubusercontent.com/3058939/99688631-e138d500-2a3a-11eb-974a-8d09d1475c28.png" />
</details>

<details><summary>Calculator I expected to see when accessing localhost:5000</summary>
<img src="https://user-images.githubusercontent.com/3058939/99689950-6f618b00-2a3c-11eb-8051-c056628d13ae.png" />
</details>



#### Expected
I would open localhost:5000 and see an error

#### Actual
Surprisingly, I was able to access localhost:5000 despite the compilation errors. However, the site is showing notecalc3's website instead of the calculator.

**Comment by bbodi** [comment]
Nice description, thanks :) 
You can access notecalc via localhost:5000/notecalc

You are right the README is not up to date, I will update it.

Thanks for your report!

**Comment by alechp** [comment]
I think useful changes would be:
1. Update readme to show install
2. Add `npx serve` to ./compile_and_run.bat
3. Add a comment about rust version required to run this (to avoid the notecalc-lib errors)


Thanks for the quick response. That worked :)
