### ISSUE TITLE
`sum` reset seems to be broken 

### ISSUE THREAD

**Issue by Dimagog** [bbodi/notecalc3#10]
Starting line with `--` does not reset `sum`
![image](https://user-images.githubusercontent.com/138993/102151999-f5e56e80-3e28-11eb-95d9-0f58e79325c7.png)

**Comment by bbodi** [comment]
Hi, the `--` has been replaced by `# Headers`, you can read about it in the [release notes](https://github.com/bbodi/notecalc3/releases/tag/v0.2.0)
