### ISSUE TITLE
Multiple Licenses support

### ISSUE THREAD

**Issue by Alecyrus** [bbodi/notecalc3#19]
Now the license of notecalc3 is AGPL-V3, which is not friendly for me want to integrate notecalc3 into my commercial project as an extra practical feature.  Could you please consider support multiple licenses? I mean, I'd love to pay for this awesome project. If you have no plan to earn profits from it, MIT license maybe more friendly.

**Comment by bbodi** [comment]
Hi,

Please contact me for further discussion (bodidev@gmail.com)
