### ISSUE TITLE
Sum reset not resetting

### ISSUE THREAD

**Issue by apfranzen** [bbodi/notecalc3#38]
Hello,

Love the project. While looking at the [homepage](https://bbodi.github.io/notecalc3/), I saw that sum could be reset with `--`:
```
Values are automatically accumulated in the sum variable.
It can be reset and set to zero by starting a line with double dash (--). 
```

In practice, it doesn't seem like sum is resetting like I would expect. Am I missing something or is this not working?

<img width="779" alt="image" src="https://user-images.githubusercontent.com/17150187/136597478-7957aaf5-ead2-44f2-8ef6-4d573fde01a7.png">

**Comment by bbodi** [comment]
Sorry, it seems the tutorial is out of date: you can reset sum using headers:
```
100
200
# Header
3
sum
```
