### ISSUE TITLE
clearing the sum variable not working

### ISSUE THREAD

**Issue by BenGood** [bbodi/notecalc3#41]
a line starting with '--' is supposed to clear the sum variable so you can start from 0. This seems to not be working. For example, in the first example on the homepage [Introduciton/features](https://bbodi.github.io/notecalc3/notecalc#eJxtVV1v2zYUfeevuA9t1qb-kO2mb3loGmQbsGVFm24Yig6gpGuLMEUKpGRF-_U7l5Idp6sB2xR5eT_OPffo3rdcaFuQiaSp0q4cSJ47q1sfqA2DcTtqPeUhLSomXR60a_WOI_ktffadPXBQMJHDnvOFUn_7Dl4cdZHJtKTFd-Hr3DjdGu_knj4Pg7DYcMil0eWMavMowY4GuBFnynV1ziHOyDcc5BaWnTNtyqJmHbvANbuWetNWsuHgY9vZGZUci2Ca1hyYWn7EDR18h5BIuJ6pJviDKVNA7-Sctkhp8F14lsGCPnHsrMRzqdRgdhVqC0Cka30NK5jbQXVNqVsuqa_YpXhUAFfABWAe5FGgPr9BUR9gb9wY1HrsAm_fRw4zQaWS5HArSnkT0DgD7HD52ddM_KjrxiIE3TFb2gZmMRwDpzoTxo3Vw1Q8bn7kUPDYSXX99FGrLKM3tMpeqjVWl3Q1Lua0xpa6P_bhF35MTqWrYaDS7NCMc0c_-CRmlN791IJrhzFHZNPSvxx8RMxsrwD-KvtdxUYXUmajQ4Jz6j_OKMvSV92MkSUJSeZokT3e3aksX411ZHmWrVZKfeItB3aFYGmN4x-keuJtYGHuefcpR4VB7y7K4JtmGoWacjQHaPs69YRLA15KAaetkDgDTrrS92jx1L3RElwOqNBy0Z48JvaKyZePy9s__rqnPQ9R9ZWxTJW3iafvf3tYqNUaQFqrA-VA55I28h_BZgPYQJYNNezBCRxdfN2sv6lfR9rq3AN4QWBGm3fj3IcJGzg6aNvxmL_Y0Ga9oA8jjbQbJiq649lMwFdGCrTgrNS7lXJGOo8APMGefC9OKPMBA1JLNueGuJra88TTP3UwOrfnHVM32u1l8N_XjII1XdNV4sSL5cCA5A1dLdbg7QfTmlxM_3f-7qW6NdsppHg6mc7pO-fq4uvb9TeBWO5GNZ8D_BdJJXKG9K0vV5vxEQO9ZwwBpppiwy5165piVyuFH9K210NMfYzjFGMTgWTZBD4Y38VntEMsEYWJlJHbM5LolixkD1u9p1LHCpi9ms9fy4E4zHlnnIjgKLcCqspSGui5Axtl5pT64k5jqx6kD15DGb3f09ur2riulVaMYik1oT1TwgeuTAF-9ZD3S1qt9_WyUq8eKngXUrmjKMEYGUH-RZ1jKiVPZIJAQjzBk2SL-mNMQpvSOMGRmNb7sMcM4lU1vVIQIddx0k9N0aRINWbNNBbbgp7Kue0ZHHteyJjpjPIu4ST6HVKEUiKMN6S-9J5xZbqkThtpbDGOBTwACKhXiJgkcWF2zoej8J-6OL01RyF4rW597ywgln1Nq59vaCujnTq6FOHLl1EwQcYiJKmwIdl9fwoBkELS4zKqK6r_WY-ne1lV6j9NhaIw)

the sum is 'Err' presumably because the units don't match.

**Comment by bbodi** [comment]
Yeah, the docs seems outdated :(
Sum is resetted automatically by headers
```
12
# this is a header which resets sum
12$ for beer
2*13$ for tickets
all spending = sum
```

**Comment by bbodi** [comment]
** The solution for this issue would be to update the docs. I won't do it for now, since I am still working on the project in the background and my version is so much different than the public version that I don't even remember how it exactly worked, and don't want to spend time on it, since the new release will contain better on-boarding experience, documentation and examples for all the new and old features as well. Though I can work on it only in my free time so it is a slow process.

**Comment by BenGood** [comment]
:) thanks @bbodi 
I'm enjoying the public version of this tool. Thanks so much for making it public.

**Comment by gustavotrott** [comment]
Is it tricky to change in the Home page as well?

![image](https://user-images.githubusercontent.com/5660191/156936387-996c862e-398c-4086-8f12-96ba25ad2b62.png)
