### ISSUE TITLE
Double dash is not clearing sum

### ISSUE THREAD

**Issue by dedrop** [bbodi/notecalc3#44]
Documentation says a line starting with a double dash should clear the sum variable. This doesn't seem to be working:

![image](https://user-images.githubusercontent.com/67775705/182693132-ea7bc170-da36-4c22-8e00-b4fd0be71979.png)

**Comment by bbodi** [comment]
Hi, yes the documentation is outdated unfortunately in this case: https://github.com/bbodi/notecalc3/issues/41
