### ISSUE TITLE
Feature-request: data synchronization

### ISSUE THREAD

**Issue by ghost** [bbodi/notecalc3#46]
Hi - I would be happy if I could save certain data somewhere like a google drive, dropbox or through protocols such as: remote storage, ftp or webdav if that's possible.  Would it be possible to have a way to synchronize my data in notecalc3?

If anyone can answer, I look forward to hearing from you.

**Comment by bbodi** [comment]
Yes this is on my list, but not planned in 0.4 (next release this year)

**Comment by ghost** [comment]
Hi bbodi.

> Yes this is on my list, but not planned in 0.4 (next release this year)

thank you for feedback.  All my questions have been answered, I will close this issue.
