### ISSUE TITLE
-- not resetting sum

### ISSUE THREAD

**Issue by nomnomaad** [bbodi/notecalc3#47]
I may be doing something wrong, but starting the line with double dash does not reset the sum.

It is not even working in the Introduction/Features note, it displays Err.

macOS Monterey Version 12.5.1 (21G83)
Safari Version 15.6.1 (17613.3.9.1.16)

![Screenshot 2022-09-05 at 19 52 26](https://user-images.githubusercontent.com/2790768/188497490-16f5178b-8dd2-4dfb-9b27-24b837f09c9a.png)

**Comment by bbodi** [comment]
Hi, yes it is a known issue :( https://github.com/bbodi/notecalc3/issues/44
