### ISSUE TITLE
License unfavourable 

### ISSUE THREAD

**Issue by charleschege** [bbodi/notecalc3#5]
The AGPL license is not favourable for widespread usage whether commercially or with a lot of other open source licences. Would you consider replacing the current license with something like Apache-2.0?

**Comment by bbodi** [comment]
Hi,

Valid concern.
I will revisit my reasoning behind the current license and will see, thanks for bringing it up.

Btw, are you in any particular situation in which the current license would be a limitation, or are you just concerned generally about it?

**Comment by charleschege** [comment]
I am generally concerned about this because your software is more likely to be used together with other software, for example it might be incorporated into a school software system where many other libraries are used, and these libraries might carry other open source or proprietary licences that might be incompatible with AGPL. If you want to commercialise this project, I suggest that you look into a business model where they have a platform as a service model but their core software is open to use
