### ISSUE TITLE
Hosted notecalc URL 404s

### ISSUE THREAD

**Issue by spiffytech** [bbodi/notecalc3#55]
I was previously accessing Notecalc from the URL https://bbodi.github.io/notecalc3/notecalc#some-hash. This now 404s, although it's still linked from the README ("Try it out")

The github [project URL](https://bbodi.github.io/notecalc3/) loads, but seems like it's a tutorial? It doesn't have any of my old data in it, a tabbed interface, etc.

How should I access my old calcs now?

**Comment by BenGood** [comment]
take a look at #52. @bbodi re-added the old version and I put a comment showing how I got my data in there.
